//! Scheme → Rust compiler.
//!
//! Compiles Scheme source into a standalone Rust program that links
//! against wispy-scheme's table and heap. The compiled output is a
//! single .rs file with inline table + heap, no external dependencies.
//!
//! Handles: define (functions + values), lambda (closure conversion),
//! if, cond, let, let*, letrec, begin, and/or, quote, set!,
//! arithmetic, list ops, tail calls (via loop).
//!
//! Does NOT handle (yet): call/cc, macros, eval, ports.
//! These require a runtime evaluator — the compiler is for
//! the "hot path" code that needs native speed.

use crate::heap::Heap;
use crate::symbol::SymbolTable;
use crate::val::Val;
use crate::table;

/// Compiler state.
pub struct Compiler {
    /// Collected top-level function definitions: (name, params, body)
    functions: Vec<(String, Vec<String>, Val)>,
    /// Top-level expressions to run in main
    main_exprs: Vec<Val>,
    /// Global variable definitions: (name, init_expr)
    globals: Vec<(String, Val)>,
    /// Functions that use the heap (cons, list, etc.)
    heap_users: Vec<String>,
}

impl Compiler {
    pub fn new() -> Self {
        Compiler {
            functions: Vec::new(),
            main_exprs: Vec::new(),
            globals: Vec::new(),
            heap_users: Vec::new(),
        }
    }

    /// Parse and collect top-level forms.
    pub fn process(&mut self, exprs: &[Val], heap: &Heap, syms: &SymbolTable) {
        for &expr in exprs {
            if heap.is_pair(expr) {
                let head = heap.car(expr);
                if heap.is_symbol(head) {
                    if let Some(name) = syms.symbol_name(head) {
                        if name == "define" {
                            self.process_define(expr, heap, syms);
                            continue;
                        }
                    }
                }
            }
            self.main_exprs.push(expr);
        }
    }

    fn process_define(&mut self, expr: Val, heap: &Heap, syms: &SymbolTable) {
        let rest = heap.cdr(expr);
        let target = heap.car(rest);

        if heap.is_symbol(target) {
            // (define x expr)
            let name = syms.symbol_name(target).unwrap_or("_").to_string();
            let init = heap.car(heap.cdr(rest));
            self.globals.push((name, init));
        } else if heap.is_pair(target) {
            // (define (f args...) body...)
            let name_sym = heap.car(target);
            let name = syms.symbol_name(name_sym).unwrap_or("_").to_string();
            let mut params = Vec::new();
            let mut p = heap.cdr(target);
            while heap.is_pair(p) {
                let param = heap.car(p);
                if let Some(pname) = syms.symbol_name(param) {
                    params.push(pname.to_string());
                }
                p = heap.cdr(p);
            }
            // Collect body (may be multiple expressions)
            let body_list = heap.cdr(rest);
            let body = if heap.cdr(body_list) == Val::NIL {
                heap.car(body_list)
            } else {
                // Wrap in begin — we'll handle this in code gen
                body_list
            };
            self.functions.push((name, params, body));
        }
    }

    /// Emit the compiled Rust program as a string.
    pub fn emit_rust(&self, heap: &Heap, syms: &SymbolTable) -> String {
        let mut out = String::new();

        // Header
        out.push_str("// Generated by wispy-scheme compiler\n");
        out.push_str("#![allow(non_snake_case, unused_variables, unused_mut, unused_parens)]\n\n");

        // Inline the Cayley table
        out.push_str("// 32×32 Cayley table (1KB)\n");
        out.push_str(&format!("const N: usize = {};\n", table::N));
        out.push_str("const TOP: u8 = 0;\nconst BOT: u8 = 1;\n");
        out.push_str(&format!("const T_PAIR: u8 = {};\n", table::T_PAIR));
        out.push_str("\n");

        // Inline the table data
        out.push_str("static CAYLEY: [[u8; 32]; 32] = ");
        out.push_str(&self.emit_table_literal());
        out.push_str(";\n\n");

        // Value type and heap
        out.push_str(RUNTIME_PRELUDE);
        out.push_str("\n");

        // Function definitions
        for (name, params, body) in &self.functions {
            let rname = rust_ident(name);
            let rparams: Vec<String> = params.iter()
                .map(|p| format!("{}: Val", rust_ident(p)))
                .collect();
            let params_str = rparams.join(", ");

            out.push_str(&format!("fn {rname}({params_str}) -> Val {{\n"));
            let body_code = self.emit_expr(*body, heap, syms, 1);
            out.push_str(&body_code);
            out.push_str("}\n\n");
        }

        // Main
        out.push_str("fn main() {\n");
        out.push_str("    heap_init();\n");

        // Global variables
        for (name, init) in &self.globals {
            let rname = rust_ident(name);
            let init_code = self.emit_expr_inline(*init, heap, syms);
            out.push_str(&format!("    let mut {rname} = {init_code};\n"));
        }
        out.push_str("\n");

        // Main expressions
        for &expr in &self.main_exprs {
            // Need to use block expressions in main so they compile as statements
            let code = self.emit_expr_inline(expr, heap, syms);
            out.push_str(&format!("    {{ let _ = {code}; }}\n"));
        }

        out.push_str("}\n");
        out
    }

    fn emit_table_literal(&self) -> String {
        let mut s = String::from("[\n");
        for i in 0..table::N {
            s.push_str("    [");
            for j in 0..table::N {
                if j > 0 { s.push_str(", "); }
                s.push_str(&format!("{}", table::CAYLEY[i][j]));
            }
            s.push_str("],\n");
        }
        s.push_str("]");
        s
    }

    /// Emit an expression as a Rust return statement.
    fn emit_expr(&self, expr: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let pad = "    ".repeat(indent);

        if expr.is_fixnum() {
            return format!("{pad}Val::fixnum({})\n", expr.as_fixnum().unwrap());
        }

        if expr == Val::NIL {
            return format!("{pad}Val::NIL\n");
        }

        if !expr.is_rib() {
            return format!("{pad}Val::NIL\n");
        }

        let tag = heap.tag(expr);

        if tag == table::T_SYM {
            let name = syms.symbol_name(expr).unwrap_or("_");
            return format!("{pad}{}\n", rust_ident(name));
        }

        if tag != table::T_PAIR {
            return format!("{pad}Val::NIL\n");
        }

        let head = heap.car(expr);
        let rest = heap.cdr(expr);

        if heap.is_symbol(head) {
            let name = syms.symbol_name(head).unwrap_or("");

            match name {
                "quote" => {
                    let datum = heap.car(rest);
                    let d = self.emit_datum(datum, heap, syms);
                    return format!("{pad}{d}\n");
                }

                "if" => {
                    let test = heap.car(rest);
                    let rest2 = heap.cdr(rest);
                    let conseq = heap.car(rest2);
                    let alt = heap.car(heap.cdr(rest2));
                    let test_code = self.emit_expr_inline(test, heap, syms);
                    let t_code = self.emit_expr(conseq, heap, syms, indent + 1);
                    let f_code = self.emit_expr(alt, heap, syms, indent + 1);
                    return format!(
                        "{pad}if is_true({test_code}) {{\n{t_code}{pad}}} else {{\n{f_code}{pad}}}\n"
                    );
                }

                "begin" => {
                    return self.emit_begin(rest, heap, syms, indent);
                }

                "let" => {
                    let bindings = heap.car(rest);
                    let body = heap.cdr(rest);
                    let mut out = String::new();
                    out.push_str(&format!("{pad}{{\n"));
                    let mut b = bindings;
                    while heap.is_pair(b) {
                        let binding = heap.car(b);
                        let var = heap.car(binding);
                        let init = heap.car(heap.cdr(binding));
                        let vname = syms.symbol_name(var).unwrap_or("_");
                        let init_code = self.emit_expr_inline(init, heap, syms);
                        out.push_str(&format!("{pad}    let {} = {};\n",
                            rust_ident(vname), init_code));
                        b = heap.cdr(b);
                    }
                    out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                    out.push_str(&format!("{pad}}}\n"));
                    return out;
                }

                "cond" => {
                    return self.emit_cond(rest, heap, syms, indent);
                }

                "and" => {
                    if rest == Val::NIL {
                        return format!("{pad}Val::fixnum(1) // #t\n");
                    }
                    let mut parts = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        parts.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    let chain = parts.join(" && is_true(") + ")".repeat(parts.len() - 1).as_str();
                    // Simplified: just check truthiness
                    return format!("{pad}{{ let _and = {}; _and }}\n",
                        self.emit_and_chain(&parts));
                }

                "+" | "-" | "*" | "/" | "quotient" | "remainder" | "modulo" => {
                    return self.emit_arith(name, rest, heap, syms, &pad);
                }

                "=" | "<" | ">" | "<=" | ">=" | "even?" | "odd?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    match name {
                        "even?" => return format!("{pad}bool_to_val({a}.as_fixnum().unwrap() % 2 == 0)\n"),
                        "odd?" => return format!("{pad}bool_to_val({a}.as_fixnum().unwrap() % 2 != 0)\n"),
                        _ => {
                            let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                            let op = match name {
                                "=" => "==", "<" => "<", ">" => ">",
                                "<=" => "<=", ">=" => ">=", _ => "=="
                            };
                            return format!("{pad}bool_to_val({a}.as_fixnum().unwrap() {op} {b}.as_fixnum().unwrap())\n");
                        }
                    }
                }

                "null?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val(({a}) == Val::NIL)\n");
                }

                "pair?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val(({a}) != Val::NIL && !({a}).is_fixnum())\n");
                }

                "zero?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a}.as_fixnum() == Some(0))\n");
                }

                "cons" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}cons({a}, {b})\n");
                }

                "car" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}car({a})\n");
                }

                "cdr" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}cdr({a})\n");
                }

                "display" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}{{ let v = {a}; display(v); Val::NIL }}\n");
                }

                "newline" => {
                    return format!("{pad}{{ println!(); Val::NIL }}\n");
                }

                "set!" => {
                    let var = heap.car(rest);
                    let val_expr = heap.car(heap.cdr(rest));
                    let vname = syms.symbol_name(var).unwrap_or("_");
                    let val_code = self.emit_expr_inline(val_expr, heap, syms);
                    return format!("{pad}{} = {val_code};\n{pad}Val::NIL\n",
                        rust_ident(vname));
                }

                "list" => {
                    if rest == Val::NIL {
                        return format!("{pad}Val::NIL\n");
                    }
                    // Build list from args
                    let mut args = Vec::new();
                    let mut a = rest;
                    while heap.is_pair(a) {
                        args.push(self.emit_expr_inline(heap.car(a), heap, syms));
                        a = heap.cdr(a);
                    }
                    let mut s = "Val::NIL".to_string();
                    for arg in args.iter().rev() {
                        s = format!("cons({arg}, {s})");
                    }
                    return format!("{pad}{s}\n");
                }

                "not" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val(!is_true({a}))\n");
                }

                "pair?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a} != Val::NIL && !{a}.is_fixnum())\n");
                }

                _ => {
                    // Function call
                    let fname = rust_ident(name);
                    let mut args = Vec::new();
                    let mut a = rest;
                    while heap.is_pair(a) {
                        args.push(self.emit_expr_inline(heap.car(a), heap, syms));
                        a = heap.cdr(a);
                    }
                    let args_str = args.join(", ");
                    return format!("{pad}{fname}({args_str})\n");
                }
            }
        }

        // Generic function call (head is not a symbol)
        format!("{pad}Val::NIL // unhandled\n")
    }

    /// Emit an expression as an inline Rust expression (no trailing newline).
    fn emit_expr_inline(&self, expr: Val, heap: &Heap, syms: &SymbolTable) -> String {
        if expr.is_fixnum() {
            return format!("Val::fixnum({})", expr.as_fixnum().unwrap());
        }
        if expr == Val::NIL {
            return "Val::NIL".to_string();
        }
        if !expr.is_rib() {
            return "Val::NIL".to_string();
        }
        let tag = heap.tag(expr);
        if tag == table::T_SYM {
            return rust_ident(syms.symbol_name(expr).unwrap_or("_"));
        }
        if tag != table::T_PAIR {
            return "Val::NIL".to_string();
        }

        let head = heap.car(expr);
        let rest = heap.cdr(expr);

        if heap.is_symbol(head) {
            let name = syms.symbol_name(head).unwrap_or("");
            match name {
                "+" | "-" | "*" | "/" | "quotient" | "remainder" | "modulo" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    let op = match name { "+" => "+", "-" => "-", "*" => "*",
                                          "/" | "quotient" => "/", "remainder" | "modulo" => "%", _ => "+" };
                    return format!("Val::fixnum({a}.as_fixnum().unwrap() {op} {b}.as_fixnum().unwrap())");
                }
                "=" | "<" | ">" | "<=" | ">=" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    let op = match name { "=" => "==", "<" => "<", ">" => ">",
                                          "<=" => "<=", ">=" => ">=", _ => "==" };
                    return format!("bool_to_val({a}.as_fixnum().unwrap() {op} {b}.as_fixnum().unwrap())");
                }
                "cons" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("cons({a}, {b})");
                }
                "car" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("car({a})");
                }
                "cdr" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("cdr({a})");
                }
                "if" => {
                    let test = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let r2 = heap.cdr(rest);
                    let c = self.emit_expr_inline(heap.car(r2), heap, syms);
                    let a = self.emit_expr_inline(heap.car(heap.cdr(r2)), heap, syms);
                    return format!("if is_true({test}) {{ {c} }} else {{ {a} }}");
                }
                "null?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a} == Val::NIL)");
                }
                "quote" => {
                    let datum = heap.car(rest);
                    return self.emit_datum(datum, heap, syms);
                }
                "display" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{{ display({a}); Val::NIL }}");
                }
                "newline" => {
                    return "{ println!(); Val::NIL }".to_string();
                }
                "zero?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.as_fixnum() == Some(0))");
                }
                _ => {
                    let fname = rust_ident(name);
                    let mut args = Vec::new();
                    let mut a = rest;
                    while heap.is_pair(a) {
                        args.push(self.emit_expr_inline(heap.car(a), heap, syms));
                        a = heap.cdr(a);
                    }
                    return format!("{fname}({})", args.join(", "));
                }
            }
        }

        "Val::NIL".to_string()
    }

    fn emit_begin(&self, mut body: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let mut out = String::new();
        while heap.is_pair(body) {
            let is_last = heap.cdr(body) == Val::NIL;
            if is_last {
                out.push_str(&self.emit_expr(heap.car(body), heap, syms, indent));
            } else {
                let code = self.emit_expr_inline(heap.car(body), heap, syms);
                let pad = "    ".repeat(indent);
                out.push_str(&format!("{pad}{code};\n"));
            }
            body = heap.cdr(body);
        }
        out
    }

    fn emit_cond(&self, mut clauses: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let mut out = String::new();
        let mut first = true;

        while heap.is_pair(clauses) {
            let clause = heap.car(clauses);
            let test = heap.car(clause);
            let body = heap.cdr(clause);

            if heap.is_symbol(test) && syms.sym_eq(test, "else") {
                out.push_str(&format!("{pad}}} else {{\n"));
                out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                out.push_str(&format!("{pad}}}\n"));
                return out;
            }

            let test_code = self.emit_expr_inline(test, heap, syms);
            if first {
                out.push_str(&format!("{pad}if is_true({test_code}) {{\n"));
                first = false;
            } else {
                out.push_str(&format!("{pad}}} else if is_true({test_code}) {{\n"));
            }
            out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
            clauses = heap.cdr(clauses);
        }

        if !first {
            out.push_str(&format!("{pad}}} else {{\n{pad}    Val::NIL\n{pad}}}\n"));
        }
        out
    }

    fn emit_arith(&self, op: &str, rest: Val, heap: &Heap, syms: &SymbolTable, pad: &str) -> String {
        let a = self.emit_expr_inline(heap.car(rest), heap, syms);
        let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
        let rust_op = match op {
            "+" => "+", "-" => "-", "*" => "*", "/" => "/",
            "quotient" => "/", "remainder" => "%", "modulo" => "%",
            _ => "+"
        };
        format!("{pad}Val::fixnum({a}.as_fixnum().unwrap() {rust_op} {b}.as_fixnum().unwrap())\n")
    }

    fn emit_and_chain(&self, parts: &[String]) -> String {
        if parts.is_empty() { return "Val::fixnum(1)".to_string(); }
        if parts.len() == 1 { return parts[0].clone(); }
        let mut s = format!("{{ let _v = {}; if !is_true(_v) {{ _v }}", parts[0]);
        for p in &parts[1..parts.len()-1] {
            s.push_str(&format!(" else {{ let _v = {}; if !is_true(_v) {{ _v }}", p));
        }
        s.push_str(&format!(" else {{ {} }}", parts.last().unwrap()));
        for _ in 0..parts.len()-1 { s.push_str(" }"); }
        s.push_str(" }");
        s
    }

    fn emit_datum(&self, datum: Val, heap: &Heap, syms: &SymbolTable) -> String {
        if datum.is_fixnum() {
            return format!("Val::fixnum({})", datum.as_fixnum().unwrap());
        }
        if datum == Val::NIL {
            return "Val::NIL".to_string();
        }
        if heap.is_symbol(datum) {
            // Quoted symbol — for now, emit as a fixnum hash
            let name = syms.symbol_name(datum).unwrap_or("_");
            let hash = name.bytes().fold(0i64, |acc, b| acc.wrapping_mul(31).wrapping_add(b as i64));
            return format!("Val::fixnum({hash}) /* '{name} */");
        }
        "Val::NIL".to_string()
    }
}

/// Convert a Scheme identifier to a valid Rust identifier.
fn rust_ident(name: &str) -> String {
    let mut s = String::new();
    for c in name.chars() {
        match c {
            '-' => s.push('_'),
            '?' => s.push_str("_p"),
            '!' => s.push_str("_bang"),
            '>' => s.push_str("_to_"),
            '<' => s.push_str("_lt_"),
            '=' => s.push_str("_eq_"),
            '*' => s.push_str("_star_"),
            '+' => s.push_str("_plus_"),
            '/' => s.push_str("_div_"),
            _ => s.push(c),
        }
    }
    // Avoid Rust keywords
    match s.as_str() {
        "type" => "type_".to_string(),
        "match" => "match_".to_string(),
        "loop" => "loop_".to_string(),
        "fn" => "fn_".to_string(),
        "let" => "let_".to_string(),
        "if" => "if_".to_string(),
        "else" => "else_".to_string(),
        "return" => "return_".to_string(),
        "mod" => "mod_".to_string(),
        _ => s,
    }
}

/// The minimal runtime that gets inlined into compiled output.
/// Uses a global heap to avoid mutable borrow issues in nested expressions.
const RUNTIME_PRELUDE: &str = r#"
// ── Inline runtime ───────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq)]
struct Val(i64);

impl Val {
    const NIL: Val = Val(0);

    #[inline(always)]
    const fn fixnum(n: i64) -> Val { Val((n << 1) | 1) }

    #[inline(always)]
    const fn rib(idx: usize) -> Val { Val((idx as i64) << 1) }

    #[inline(always)]
    fn is_fixnum(self) -> bool { (self.0 & 1) != 0 }

    #[inline(always)]
    fn as_fixnum(self) -> Option<i64> {
        if self.is_fixnum() { Some(self.0 >> 1) } else { None }
    }

    #[inline(always)]
    fn as_rib(self) -> usize { (self.0 >> 1) as usize }
}

#[derive(Clone, Copy)]
struct Rib { car: Val, cdr: Val, tag: u8 }

static mut HEAP: Vec<Rib> = Vec::new();

fn heap_init() {
    unsafe { HEAP = Vec::with_capacity(65536);
             HEAP.push(Rib { car: Val::NIL, cdr: Val::NIL, tag: TOP }); }
}

#[inline]
fn cons(car: Val, cdr: Val) -> Val {
    unsafe {
        let idx = HEAP.len();
        HEAP.push(Rib { car, cdr, tag: T_PAIR });
        Val::rib(idx)
    }
}

#[inline(always)]
fn car(v: Val) -> Val {
    if v.is_fixnum() || v == Val::NIL { return Val::NIL; }
    unsafe { HEAP[v.as_rib()].car }
}

#[inline(always)]
fn cdr(v: Val) -> Val {
    if v.is_fixnum() || v == Val::NIL { return Val::NIL; }
    unsafe { HEAP[v.as_rib()].cdr }
}

#[inline(always)]
fn is_true(v: Val) -> bool {
    v != Val::NIL && v.0 != 0
}

#[inline(always)]
fn bool_to_val(b: bool) -> Val {
    if b { Val::fixnum(1) } else { Val::NIL }
}

fn display(v: Val) {
    if v == Val::NIL { print!("()"); }
    else if let Some(n) = v.as_fixnum() { print!("{n}"); }
    else { print!("<rib>"); }
}
"#;

/// Compile a Scheme source string to a Rust program string.
pub fn compile(src: &str) -> String {
    let mut heap = Heap::new();
    let mut syms = SymbolTable::new();
    let exprs = crate::reader::read_all(src, &mut heap, &mut syms)
        .unwrap_or_default();
    let mut compiler = Compiler::new();
    compiler.process(&exprs, &heap, &syms);
    compiler.emit_rust(&heap, &syms)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compile_fib() {
        let code = compile("
            (define (fib n)
              (if (< n 2) n
                  (+ (fib (- n 1)) (fib (- n 2)))))
            (display (fib 10))
            (newline)
        ");
        assert!(code.contains("fn fib("));
        assert!(code.contains("fn main()"));
        assert!(code.contains("display"));
    }

    #[test]
    fn compile_arithmetic() {
        let code = compile("(display (+ 3 4))");
        assert!(code.contains("Val::fixnum(3)"));
        assert!(code.contains("Val::fixnum(4)"));
    }

    #[test]
    fn compiled_output_compiles() {
        // Write the compiled output to a temp file and compile it with rustc
        let code = compile("
            (define (fact n)
              (if (= n 0) 1
                  (* n (fact (- n 1)))))
            (display (fact 10))
            (newline)
        ");

        let path = "/tmp/kamea_test_compiled.rs";
        std::fs::write(path, &code).unwrap();
        let output = std::process::Command::new("rustc")
            .args(["-O", "-o", "/tmp/kamea_test_compiled", path])
            .output()
            .expect("failed to run rustc");

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            panic!("rustc failed:\n{stderr}\n\nGenerated code:\n{code}");
        }

        // Run it and check output
        let run = std::process::Command::new("/tmp/kamea_test_compiled")
            .output()
            .expect("failed to run compiled program");
        let stdout = String::from_utf8_lossy(&run.stdout);
        assert_eq!(stdout.trim(), "3628800");
    }

    #[test]
    fn compiled_nqueens() {
        let code = compile("
            (define (abs-diff a b) (if (> a b) (- a b) (- b a)))
            (define (safe? queen dist placed)
              (if (null? placed) 42
                (let ((q (car placed)))
                  (cond ((= queen q) '())
                        ((= (abs-diff queen q) dist) '())
                        (else (safe? queen (+ dist 1) (cdr placed)))))))
            (define (nqueens-count n row placed)
              (if (= row n) 1
                (count-cols n 0 row placed)))
            (define (count-cols n col row placed)
              (if (= col n) 0
                (+ (if (safe? col 1 placed)
                     (nqueens-count n (+ row 1) (cons col placed))
                     0)
                   (count-cols n (+ col 1) row placed))))
            (define (nqueens n) (nqueens-count n 0 '()))
            (display (nqueens 8))
            (newline)
        ");

        let path = "/tmp/kamea_nqueens_compiled.rs";
        std::fs::write(path, &code).unwrap();
        let output = std::process::Command::new("rustc")
            .args(["-O", "-o", "/tmp/kamea_nqueens_compiled", path])
            .output()
            .expect("failed to run rustc");

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            panic!("rustc failed:\n{stderr}\n\nGenerated code:\n{code}");
        }

        let run = std::process::Command::new("/tmp/kamea_nqueens_compiled")
            .output()
            .expect("failed to run compiled program");
        let stdout = String::from_utf8_lossy(&run.stdout);
        assert_eq!(stdout.trim(), "92");
    }
}
