//! The 64×64 Cayley table.
//!
//! 4,096 bytes. Every operation on immediate values is a single
//! array index into this table. Type dispatch, fixnum arithmetic,
//! type predicates — all table lookups.
//!
//! The table is `const` and lives in `.rodata` (flash on embedded).

/// Number of elements in the algebra.
pub const N: usize = 64;

// ── Element indices ──────────────────────────────────────────────

// Algebraic core
pub const TOP: u8 = 0;    // ⊤, nil, '()
pub const BOT: u8 = 1;    // ⊥, #f, error
pub const Q: u8 = 2;      // quote / encoder
pub const E: u8 = 3;      // eval / decoder
pub const CAR: u8 = 4;    // first projection
pub const CDR: u8 = 5;    // second projection
pub const CONS: u8 = 6;   // pair constructor

// Control
pub const RHO: u8 = 7;    // branch / conditional
pub const APPLY: u8 = 8;  // explicit apply
pub const CC: u8 = 9;     // call/cc

// Classifier and Y combinator
pub const TAU: u8 = 10;   // classifier / type predicate
pub const Y: u8 = 11;     // Y combinator (fixed point)

// Type tags
pub const T_PAIR: u8 = 12;
pub const T_SYM: u8 = 13;
pub const T_CHAR: u8 = 14;
pub const T_VEC: u8 = 15;
pub const T_STR: u8 = 16;
pub const T_CLS: u8 = 17;

// Immediate fixnums: elements 18..49 represent integers 0..31
pub const FIXNUM_BASE: u8 = 18;
pub const FIXNUM_COUNT: u8 = 32;

/// Element index for immediate fixnum n (0 <= n <= 31).
#[inline(always)]
pub const fn fixnum(n: u8) -> u8 {
    FIXNUM_BASE + n
}

/// Integer value of a fixnum element, or None if not a fixnum.
#[inline(always)]
pub const fn fixnum_val(elem: u8) -> Option<u8> {
    if elem >= FIXNUM_BASE && elem < FIXNUM_BASE + FIXNUM_COUNT {
        Some(elem - FIXNUM_BASE)
    } else {
        None
    }
}

// Built-in symbols
pub const SYM_LAMBDA: u8 = 50;
pub const SYM_IF: u8 = 51;
pub const SYM_DEFINE: u8 = 52;
pub const SYM_QUOTE: u8 = 53;
pub const SYM_SET: u8 = 54;
pub const SYM_BEGIN: u8 = 55;
pub const SYM_COND: u8 = 56;
pub const SYM_ELSE: u8 = 57;

// Special values
pub const TRUE: u8 = 58;  // #t
pub const EOF: u8 = 59;   // eof-object
pub const VOID: u8 = 60;  // void / unspecified
pub const TAIL: u8 = 61;  // tail-call marker

// ── The table ────────────────────────────────────────────────────

/// The 64×64 Cayley table.
///
/// `CAYLEY[a][b]` is the result of applying element `a` to element `b`.
///
/// Generated by `table_build.py` from a Z3-verified 12×12 core.
/// Core axioms verified: absorbers, extensionality, Q/E retraction,
/// E-transparency, classifier dichotomy, branch, composition, Y.
include!("../../../src/cayley_64.rs");

/// Apply element `a` to element `b` via the Cayley table.
#[inline(always)]
pub fn dot(a: u8, b: u8) -> u8 {
    CAYLEY[a as usize][b as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn absorber_top() {
        for j in 0..N as u8 {
            assert_eq!(dot(TOP, j), TOP, "⊤·{j} should be ⊤");
        }
    }

    #[test]
    fn absorber_bot() {
        for j in 0..N as u8 {
            assert_eq!(dot(BOT, j), BOT, "⊥·{j} should be ⊥");
        }
    }

    #[test]
    fn fixnum_addition() {
        for a in 0u8..32 {
            for b in 0u8..32 {
                let expected = if a + b <= 31 {
                    fixnum(a + b)
                } else {
                    BOT
                };
                assert_eq!(
                    dot(fixnum(a), fixnum(b)),
                    expected,
                    "{a}+{b} failed"
                );
            }
        }
    }

    #[test]
    fn classifier_types() {
        assert_eq!(dot(TAU, TOP), TOP);
        assert_eq!(dot(TAU, BOT), BOT);
        assert_eq!(dot(TAU, TRUE), TRUE);
        assert_eq!(dot(TAU, T_PAIR), T_PAIR);
        assert_eq!(dot(TAU, T_SYM), T_SYM);
        assert_eq!(dot(TAU, fixnum(5)), fixnum(0)); // number marker
    }

    #[test]
    fn car_type_dispatch() {
        assert_eq!(dot(CAR, T_PAIR), T_PAIR); // car of pair → valid
        assert_eq!(dot(CAR, fixnum(3)), BOT);  // car of number → error
        assert_eq!(dot(CAR, T_SYM), BOT);      // car of symbol → error
    }

    #[test]
    fn e_transparency() {
        assert_eq!(dot(E, TOP), TOP);
        assert_eq!(dot(E, BOT), BOT);
    }

    #[test]
    fn extensionality() {
        // All 64 rows must be distinct
        let mut rows: Vec<Vec<u8>> = Vec::new();
        for i in 0..N {
            rows.push(CAYLEY[i].to_vec());
        }
        rows.sort();
        rows.dedup();
        assert_eq!(rows.len(), N, "not all rows are distinct");
    }

    // ── Core sub-algebra axioms (Z3-verified, now Rust-tested) ──

    const CORE: [u8; 10] = [Q, E, CAR, CDR, CONS, RHO, APPLY, CC, TAU, Y];

    #[test]
    fn retraction_qe() {
        // E(Q(x)) = x and Q(E(x)) = x for all core elements
        for &x in &CORE {
            assert_eq!(dot(E, dot(Q, x)), x,
                "E(Q({x})) should be {x}");
            assert_eq!(dot(Q, dot(E, x)), x,
                "Q(E({x})) should be {x}");
        }
    }

    #[test]
    fn classifier_dichotomy() {
        // τ maps core to {TOP, BOT}
        for &x in &CORE {
            let tx = dot(TAU, x);
            assert!(tx == TOP || tx == BOT,
                "τ({x}) = {tx}, expected TOP or BOT");
        }
        // Both values hit
        let tops = CORE.iter().filter(|&&x| dot(TAU, x) == TOP).count();
        let bots = CORE.iter().filter(|&&x| dot(TAU, x) == BOT).count();
        assert!(tops >= 2, "τ=⊤ count {tops} < 2");
        assert!(bots >= 2, "τ=⊥ count {bots} < 2");
    }

    #[test]
    fn branch() {
        // ρ·x = car·x if τ·x = ⊤, else ρ·x = cons·x
        for &x in &CORE {
            if dot(TAU, x) == TOP {
                assert_eq!(dot(RHO, x), dot(CAR, x),
                    "ρ({x}) should equal car({x}) when τ({x})=⊤");
            } else {
                assert_eq!(dot(RHO, x), dot(CONS, x),
                    "ρ({x}) should equal cons({x}) when τ({x})=⊥");
            }
        }
    }

    #[test]
    fn composition() {
        // cdr·x = ρ·(cons·x) for all core elements
        for &x in &CORE {
            assert_eq!(dot(CDR, x), dot(RHO, dot(CONS, x)),
                "cdr({x}) should equal ρ(cons({x}))");
        }
    }

    #[test]
    fn cons_core_preserving() {
        // cons maps core to core (non-absorbers)
        for &x in &CORE {
            let gx = dot(CONS, x);
            assert!(gx >= 2, "cons({x}) = {gx}, should be non-absorber");
        }
    }

    #[test]
    fn y_fixed_point() {
        // Y(ρ) = ρ(Y(ρ)) and Y(ρ) is non-absorber
        let yp = dot(Y, RHO);
        assert!(yp >= 2, "Y(ρ) = {yp}, should be non-absorber");
        assert_eq!(dot(RHO, yp), yp, "ρ(Y(ρ)) should equal Y(ρ)");
    }
}
