//! Scheme → Rust compiler.
//!
//! Compiles Scheme source into a standalone Rust program that links
//! against wispy-scheme's table and heap. The compiled output is a
//! single .rs file with inline table + heap, no external dependencies.
//!
//! Handles: define (functions + values), lambda (closure conversion),
//! if, cond, let, let*, letrec, begin, and/or, quote, set!,
//! arithmetic, list ops, tail calls (via loop).
//!
//! Does NOT handle (yet): call/cc, macros, eval, ports.
//! These require a runtime evaluator — the compiler is for
//! the "hot path" code that needs native speed.

use crate::heap::Heap;
use crate::symbol::SymbolTable;
use crate::val::Val;
use crate::table;

/// Compiler state.
pub struct Compiler {
    /// Collected top-level function definitions: (name, params, body)
    functions: Vec<(String, Vec<String>, Val)>,
    /// Top-level expressions to run in main
    main_exprs: Vec<Val>,
    /// Global variable definitions: (name, init_expr)
    globals: Vec<(String, Val)>,
}

impl Compiler {
    pub fn new() -> Self {
        Compiler {
            functions: Vec::new(),
            main_exprs: Vec::new(),
            globals: Vec::new(),
        }
    }

    /// Parse and collect top-level forms.
    pub fn process(&mut self, exprs: &[Val], heap: &Heap, syms: &SymbolTable) {
        for &expr in exprs {
            if heap.is_pair(expr) {
                let head = heap.car(expr);
                if heap.is_symbol(head) {
                    if let Some(name) = syms.symbol_name(head) {
                        if name == "define" {
                            self.process_define(expr, heap, syms);
                            continue;
                        }
                    }
                }
            }
            self.main_exprs.push(expr);
        }
    }

    fn process_define(&mut self, expr: Val, heap: &Heap, syms: &SymbolTable) {
        let rest = heap.cdr(expr);
        let target = heap.car(rest);

        if heap.is_symbol(target) {
            // (define x expr)
            let name = syms.symbol_name(target).unwrap_or("_").to_string();
            let init = heap.car(heap.cdr(rest));
            self.globals.push((name, init));
        } else if heap.is_pair(target) {
            // (define (f args...) body...)
            let name_sym = heap.car(target);
            let name = syms.symbol_name(name_sym).unwrap_or("_").to_string();
            let mut params = Vec::new();
            let mut p = heap.cdr(target);
            while heap.is_pair(p) {
                let param = heap.car(p);
                if let Some(pname) = syms.symbol_name(param) {
                    params.push(pname.to_string());
                }
                p = heap.cdr(p);
            }
            // Collect body (may be multiple expressions)
            let body_list = heap.cdr(rest);
            let body = if heap.cdr(body_list) == Val::NIL {
                heap.car(body_list)
            } else {
                // Wrap in begin — we'll handle this in code gen
                body_list
            };
            self.functions.push((name, params, body));
        }
    }

    /// Emit the compiled Rust program as a string.
    pub fn emit_rust(&self, heap: &Heap, syms: &SymbolTable) -> String {
        let mut out = String::new();

        // Header
        out.push_str("// Generated by wispy-scheme compiler\n");
        out.push_str("#![allow(non_snake_case, unused_variables, unused_mut, unused_parens)]\n\n");

        // Inline the Cayley table
        out.push_str("// 32×32 Cayley table (1KB)\n");
        out.push_str(&format!("const N: usize = {};\n", table::N));
        out.push_str("const TOP: u8 = 0;\nconst BOT: u8 = 1;\n");
        out.push_str(&format!("const T_PAIR: u8 = {};\n", table::T_PAIR));
        out.push_str("\n");

        // Inline the table data
        out.push_str("static CAYLEY: [[u8; 32]; 32] = ");
        out.push_str(&self.emit_table_literal());
        out.push_str(";\n\n");

        // Value type and heap
        out.push_str(RUNTIME_PRELUDE);
        out.push_str("\n");

        // Function definitions
        for (name, params, body) in &self.functions {
            let rname = rust_ident(name);
            let rparams: Vec<String> = params.iter()
                .map(|p| format!("{}: Val", rust_ident(p)))
                .collect();
            let params_str = rparams.join(", ");

            out.push_str(&format!("fn {rname}({params_str}) -> Val {{\n"));
            let body_code = self.emit_expr(*body, heap, syms, 1);
            out.push_str(&body_code);
            out.push_str("}\n\n");
        }

        // Main
        out.push_str("fn main() {\n");
        out.push_str("    heap_init();\n");

        // Global variables
        for (name, init) in &self.globals {
            let rname = rust_ident(name);
            let init_code = self.emit_expr_inline(*init, heap, syms);
            out.push_str(&format!("    let mut {rname} = {init_code};\n"));
        }
        out.push_str("\n");

        // Main expressions
        for &expr in &self.main_exprs {
            // Need to use block expressions in main so they compile as statements
            let code = self.emit_expr_inline(expr, heap, syms);
            out.push_str(&format!("    {{ let _ = {code}; }}\n"));
        }

        out.push_str("}\n");
        out
    }

    fn emit_table_literal(&self) -> String {
        let mut s = String::from("[\n");
        for i in 0..table::N {
            s.push_str("    [");
            for j in 0..table::N {
                if j > 0 { s.push_str(", "); }
                s.push_str(&format!("{}", table::CAYLEY[i][j]));
            }
            s.push_str("],\n");
        }
        s.push_str("]");
        s
    }

    /// Emit an expression as a Rust return statement.
    fn emit_expr(&self, expr: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let pad = "    ".repeat(indent);

        if expr.is_fixnum() {
            return format!("{pad}Val::fixnum({})\n", expr.as_fixnum().unwrap());
        }

        if expr == Val::NIL {
            return format!("{pad}Val::NIL\n");
        }

        if !expr.is_rib() {
            return format!("{pad}Val::NIL\n");
        }

        let tag = heap.tag(expr);

        if tag == table::T_SYM {
            let name = syms.symbol_name(expr).unwrap_or("_");
            return format!("{pad}{}\n", rust_ident(name));
        }

        if tag != table::T_PAIR {
            return format!("{pad}Val::NIL\n");
        }

        let head = heap.car(expr);
        let rest = heap.cdr(expr);

        if heap.is_symbol(head) {
            let name = syms.symbol_name(head).unwrap_or("");

            match name {
                "quote" => {
                    let datum = heap.car(rest);
                    let d = self.emit_datum(datum, heap, syms);
                    return format!("{pad}{d}\n");
                }

                "if" => {
                    let test = heap.car(rest);
                    let rest2 = heap.cdr(rest);
                    let conseq = heap.car(rest2);
                    let alt = heap.car(heap.cdr(rest2));
                    let test_code = self.emit_expr_inline(test, heap, syms);
                    let t_code = self.emit_expr(conseq, heap, syms, indent + 1);
                    let f_code = self.emit_expr(alt, heap, syms, indent + 1);
                    return format!(
                        "{pad}if is_true({test_code}) {{\n{t_code}{pad}}} else {{\n{f_code}{pad}}}\n"
                    );
                }

                "begin" => {
                    return self.emit_begin(rest, heap, syms, indent);
                }

                "let" => {
                    let bindings = heap.car(rest);
                    let body = heap.cdr(rest);
                    let mut out = String::new();
                    out.push_str(&format!("{pad}{{\n"));
                    let mut b = bindings;
                    while heap.is_pair(b) {
                        let binding = heap.car(b);
                        let var = heap.car(binding);
                        let init = heap.car(heap.cdr(binding));
                        let vname = syms.symbol_name(var).unwrap_or("_");
                        let init_code = self.emit_expr_inline(init, heap, syms);
                        out.push_str(&format!("{pad}    let {} = {};\n",
                            rust_ident(vname), init_code));
                        b = heap.cdr(b);
                    }
                    out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                    out.push_str(&format!("{pad}}}\n"));
                    return out;
                }

                "let*" => {
                    let bindings = heap.car(rest);
                    let body = heap.cdr(rest);
                    let mut out = String::new();
                    out.push_str(&format!("{pad}{{\n"));
                    let mut b = bindings;
                    while heap.is_pair(b) {
                        let binding = heap.car(b);
                        let var = heap.car(binding);
                        let init = heap.car(heap.cdr(binding));
                        let vname = syms.symbol_name(var).unwrap_or("_");
                        let init_code = self.emit_expr_inline(init, heap, syms);
                        out.push_str(&format!("{pad}    let {vn} = {init_code};\n",
                            vn = rust_ident(vname)));
                        b = heap.cdr(b);
                    }
                    out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                    out.push_str(&format!("{pad}}}\n"));
                    return out;
                }

                "letrec" => {
                    let bindings = heap.car(rest);
                    let body = heap.cdr(rest);
                    let mut out = String::new();
                    out.push_str(&format!("{pad}{{\n"));
                    // First pass: declare all as mut NIL
                    let mut b = bindings;
                    while heap.is_pair(b) {
                        let binding = heap.car(b);
                        let var = heap.car(binding);
                        let vname = syms.symbol_name(var).unwrap_or("_");
                        out.push_str(&format!("{pad}    let mut {} = Val::NIL;\n",
                            rust_ident(vname)));
                        b = heap.cdr(b);
                    }
                    // Second pass: assign
                    b = bindings;
                    while heap.is_pair(b) {
                        let binding = heap.car(b);
                        let var = heap.car(binding);
                        let init = heap.car(heap.cdr(binding));
                        let vname = syms.symbol_name(var).unwrap_or("_");
                        let init_code = self.emit_expr_inline(init, heap, syms);
                        out.push_str(&format!("{pad}    {} = {init_code};\n",
                            rust_ident(vname)));
                        b = heap.cdr(b);
                    }
                    out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                    out.push_str(&format!("{pad}}}\n"));
                    return out;
                }

                "cond" => {
                    return self.emit_cond(rest, heap, syms, indent);
                }

                "case" => {
                    return self.emit_case(rest, heap, syms, indent);
                }

                "and" => {
                    if rest == Val::NIL {
                        return format!("{pad}Val::fixnum(1) // #t\n");
                    }
                    let mut parts = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        parts.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    return format!("{pad}{}\n", self.emit_and_chain(&parts));
                }

                "+" | "*" => {
                    // Variadic: (+ a b c ...) → a + b + c + ...
                    let mut args = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        args.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    if args.is_empty() {
                        return format!("{pad}Val::fixnum({})\n", if name == "+" { "0" } else { "1" });
                    }
                    let op = if name == "+" { "+" } else { "*" };
                    let chain = args.iter()
                        .map(|a| format!("{a}.as_fixnum().unwrap()"))
                        .collect::<Vec<_>>()
                        .join(&format!(" {op} "));
                    return format!("{pad}Val::fixnum({chain})\n");
                }
                "-" => {
                    let mut args = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        args.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    if args.len() == 1 {
                        return format!("{pad}Val::fixnum(-{}.as_fixnum().unwrap())\n", args[0]);
                    }
                    let first = format!("{}.as_fixnum().unwrap()", args[0]);
                    let rest_chain = args[1..].iter()
                        .map(|a| format!("{a}.as_fixnum().unwrap()"))
                        .collect::<Vec<_>>()
                        .join(" - ");
                    return format!("{pad}Val::fixnum({first} - {rest_chain})\n");
                }
                "/" | "quotient" | "remainder" | "modulo" => {
                    return self.emit_arith(name, rest, heap, syms, &pad);
                }

                "=" | "<" | ">" | "<=" | ">=" | "even?" | "odd?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    match name {
                        "even?" => return format!("{pad}bool_to_val({a}.as_fixnum().unwrap() % 2 == 0)\n"),
                        "odd?" => return format!("{pad}bool_to_val({a}.as_fixnum().unwrap() % 2 != 0)\n"),
                        _ => {
                            let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                            let op = match name {
                                "=" => "==", "<" => "<", ">" => ">",
                                "<=" => "<=", ">=" => ">=", _ => "=="
                            };
                            return format!("{pad}bool_to_val({a}.as_fixnum().unwrap() {op} {b}.as_fixnum().unwrap())\n");
                        }
                    }
                }

                "null?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val(({a}) == Val::NIL)\n");
                }

                "pair?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val(({a}) != Val::NIL && !({a}).is_fixnum())\n");
                }

                "zero?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a}.as_fixnum() == Some(0))\n");
                }

                "cons" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}cons({a}, {b})\n");
                }

                "car" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}car({a})\n");
                }

                "cdr" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}cdr({a})\n");
                }

                "display" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}{{ let v = {a}; display(v); Val::NIL }}\n");
                }

                "newline" => {
                    return format!("{pad}{{ println!(); Val::NIL }}\n");
                }

                "set!" => {
                    let var = heap.car(rest);
                    let val_expr = heap.car(heap.cdr(rest));
                    let vname = syms.symbol_name(var).unwrap_or("_");
                    let val_code = self.emit_expr_inline(val_expr, heap, syms);
                    return format!("{pad}{} = {val_code};\n{pad}Val::NIL\n",
                        rust_ident(vname));
                }

                "list" => {
                    if rest == Val::NIL {
                        return format!("{pad}Val::NIL\n");
                    }
                    // Build list from args
                    let mut args = Vec::new();
                    let mut a = rest;
                    while heap.is_pair(a) {
                        args.push(self.emit_expr_inline(heap.car(a), heap, syms));
                        a = heap.cdr(a);
                    }
                    let mut s = "Val::NIL".to_string();
                    for arg in args.iter().rev() {
                        s = format!("cons({arg}, {s})");
                    }
                    return format!("{pad}{s}\n");
                }

                "not" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val(!is_true({a}))\n");
                }

                "or" => {
                    if rest == Val::NIL {
                        return format!("{pad}Val::NIL\n");
                    }
                    let mut parts = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        parts.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    return format!("{pad}{}\n", self.emit_or_chain(&parts));
                }

                "do" => {
                    return self.emit_do(rest, heap, syms, indent);
                }

                "lambda" => {
                    // Lambda as value: emit a Rust closure
                    // For now, only handles lambdas that are immediately called
                    // or passed to known higher-order functions.
                    // Full closure conversion is future work.
                    return format!("{pad}Val::NIL // lambda-as-value not yet compiled\n");
                }

                // Additional builtins
                "abs" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}Val::fixnum({a}.as_fixnum().unwrap().abs())\n");
                }
                "max" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}Val::fixnum({a}.as_fixnum().unwrap().max({b}.as_fixnum().unwrap()))\n");
                }
                "min" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}Val::fixnum({a}.as_fixnum().unwrap().min({b}.as_fixnum().unwrap()))\n");
                }
                "expt" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}{{ let mut r = 1i64; for _ in 0..{b}.as_fixnum().unwrap() {{ r *= {a}.as_fixnum().unwrap(); }} Val::fixnum(r) }}\n");
                }
                "gcd" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}{{ let (mut a, mut b) = ({a}.as_fixnum().unwrap().abs(), {b}.as_fixnum().unwrap().abs()); while b != 0 {{ let t = b; b = a % b; a = t; }} Val::fixnum(a) }}\n");
                }
                "number?" | "integer?" | "exact?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a}.is_fixnum())\n");
                }
                "positive?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a}.as_fixnum().map_or(false, |n| n > 0))\n");
                }
                "negative?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a}.as_fixnum().map_or(false, |n| n < 0))\n");
                }
                "boolean?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}bool_to_val({a} == Val::NIL || {a} == Val::fixnum(1))\n");
                }
                "eq?" | "eqv?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}bool_to_val({a} == {b})\n");
                }
                "equal?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}bool_to_val({a} == {b})\n"); // simplified
                }
                "set-car!" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}{{ set_car({a}, {b}); Val::NIL }}\n");
                }
                "set-cdr!" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}{{ set_cdr({a}, {b}); Val::NIL }}\n");
                }
                "length" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}{{ let mut n = 0i64; let mut l = {a}; while l != Val::NIL && !l.is_fixnum() {{ n += 1; l = cdr(l); }} Val::fixnum(n) }}\n");
                }
                "append" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}append({a}, {b})\n");
                }
                "reverse" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}{{ let mut r = Val::NIL; let mut l = {a}; while l != Val::NIL && !l.is_fixnum() {{ r = cons(car(l), r); l = cdr(l); }} r }}\n");
                }
                "list-ref" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}{{ let mut l = {a}; for _ in 0..{b}.as_fixnum().unwrap() {{ l = cdr(l); }} car(l) }}\n");
                }
                "list-tail" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}{{ let mut l = {a}; for _ in 0..{b}.as_fixnum().unwrap() {{ l = cdr(l); }} l }}\n");
                }
                "write" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}{{ display({a}); Val::NIL }}\n");
                }
                "write-char" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{pad}{{ print!(\"{{}}\"  , {a}.as_fixnum().unwrap() as u8 as char); Val::NIL }}\n");
                }
                "apply" => {
                    let f = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let args = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{pad}apply_fn({f}, {args})\n");
                }

                _ => {
                    // Function call
                    let fname = rust_ident(name);
                    let mut args = Vec::new();
                    let mut a = rest;
                    while heap.is_pair(a) {
                        args.push(self.emit_expr_inline(heap.car(a), heap, syms));
                        a = heap.cdr(a);
                    }
                    let args_str = args.join(", ");
                    return format!("{pad}{fname}({args_str})\n");
                }
            }
        }

        // Generic function call (head is not a symbol)
        format!("{pad}Val::NIL // unhandled\n")
    }

    /// Emit an expression as an inline Rust expression (no trailing newline).
    fn emit_expr_inline(&self, expr: Val, heap: &Heap, syms: &SymbolTable) -> String {
        if expr.is_fixnum() {
            return format!("Val::fixnum({})", expr.as_fixnum().unwrap());
        }
        if expr == Val::NIL {
            return "Val::NIL".to_string();
        }
        if !expr.is_rib() {
            return "Val::NIL".to_string();
        }
        let tag = heap.tag(expr);
        if tag == table::T_SYM {
            return rust_ident(syms.symbol_name(expr).unwrap_or("_"));
        }
        if tag != table::T_PAIR {
            return "Val::NIL".to_string();
        }

        let head = heap.car(expr);
        let rest = heap.cdr(expr);

        if heap.is_symbol(head) {
            let name = syms.symbol_name(head).unwrap_or("");
            match name {
                "+" | "*" => {
                    let mut args = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        args.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    let op = if name == "+" { "+" } else { "*" };
                    let chain = args.iter()
                        .map(|a| format!("{a}.as_fixnum().unwrap()"))
                        .collect::<Vec<_>>()
                        .join(&format!(" {op} "));
                    return format!("Val::fixnum({chain})");
                }
                "-" | "/" | "quotient" | "remainder" | "modulo" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    if name == "-" && heap.cdr(rest) == Val::NIL {
                        return format!("Val::fixnum(-{a}.as_fixnum().unwrap())");
                    }
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    let op = match name { "-" => "-", "/" | "quotient" => "/",
                                          "remainder" | "modulo" => "%", _ => "-" };
                    return format!("Val::fixnum({a}.as_fixnum().unwrap() {op} {b}.as_fixnum().unwrap())");
                }
                "=" | "<" | ">" | "<=" | ">=" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    let op = match name { "=" => "==", "<" => "<", ">" => ">",
                                          "<=" => "<=", ">=" => ">=", _ => "==" };
                    return format!("bool_to_val({a}.as_fixnum().unwrap() {op} {b}.as_fixnum().unwrap())");
                }
                "cons" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("cons({a}, {b})");
                }
                "car" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("car({a})");
                }
                "cdr" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("cdr({a})");
                }
                "if" => {
                    let test = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let r2 = heap.cdr(rest);
                    let c = self.emit_expr_inline(heap.car(r2), heap, syms);
                    let a = self.emit_expr_inline(heap.car(heap.cdr(r2)), heap, syms);
                    return format!("if is_true({test}) {{ {c} }} else {{ {a} }}");
                }
                "null?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a} == Val::NIL)");
                }
                "pair?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a} != Val::NIL && !{a}.is_fixnum())");
                }
                "number?" | "integer?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.is_fixnum())");
                }
                "zero?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.as_fixnum() == Some(0))");
                }
                "positive?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.as_fixnum().map_or(false, |n| n > 0))");
                }
                "negative?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.as_fixnum().map_or(false, |n| n < 0))");
                }
                "even?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.as_fixnum().unwrap() % 2 == 0)");
                }
                "odd?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val({a}.as_fixnum().unwrap() % 2 != 0)");
                }
                "not" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("bool_to_val(!is_true({a}))");
                }
                "eq?" | "eqv?" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("bool_to_val({a} == {b})");
                }
                "abs" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("Val::fixnum({a}.as_fixnum().unwrap().abs())");
                }
                "max" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("Val::fixnum({a}.as_fixnum().unwrap().max({b}.as_fixnum().unwrap()))");
                }
                "min" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("Val::fixnum({a}.as_fixnum().unwrap().min({b}.as_fixnum().unwrap()))");
                }
                "length" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{{ let mut n = 0i64; let mut l = {a}; while l != Val::NIL && !l.is_fixnum() {{ n += 1; l = cdr(l); }} Val::fixnum(n) }}");
                }
                "list" => {
                    let mut args = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        args.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    let mut s = "Val::NIL".to_string();
                    for arg in args.iter().rev() {
                        s = format!("cons({arg}, {s})");
                    }
                    return s;
                }
                "reverse" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{{ let mut r = Val::NIL; let mut l = {a}; while l != Val::NIL && !l.is_fixnum() {{ r = cons(car(l), r); l = cdr(l); }} r }}");
                }
                "append" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("append({a}, {b})");
                }
                "display" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    return format!("{{ display({a}); Val::NIL }}");
                }
                "newline" => {
                    return "{ println!(); Val::NIL }".to_string();
                }
                "and" => {
                    let mut parts = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        parts.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    if parts.is_empty() { return "Val::fixnum(1)".to_string(); }
                    return self.emit_and_chain(&parts);
                }
                "or" => {
                    let mut parts = Vec::new();
                    let mut r = rest;
                    while heap.is_pair(r) {
                        parts.push(self.emit_expr_inline(heap.car(r), heap, syms));
                        r = heap.cdr(r);
                    }
                    if parts.is_empty() { return "Val::NIL".to_string(); }
                    return self.emit_or_chain(&parts);
                }
                "gcd" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{{ let (mut a, mut b) = ({a}.as_fixnum().unwrap().abs(), {b}.as_fixnum().unwrap().abs()); while b != 0 {{ let t = b; b = a % b; a = t; }} Val::fixnum(a) }}");
                }
                "set-car!" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{{ set_car({a}, {b}); Val::NIL }}");
                }
                "set-cdr!" => {
                    let a = self.emit_expr_inline(heap.car(rest), heap, syms);
                    let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
                    return format!("{{ set_cdr({a}, {b}); Val::NIL }}");
                }
                "quote" => {
                    let datum = heap.car(rest);
                    return self.emit_datum(datum, heap, syms);
                }
                _ => {
                    let fname = rust_ident(name);
                    let mut args = Vec::new();
                    let mut a = rest;
                    while heap.is_pair(a) {
                        args.push(self.emit_expr_inline(heap.car(a), heap, syms));
                        a = heap.cdr(a);
                    }
                    return format!("{fname}({})", args.join(", "));
                }
            }
        }

        "Val::NIL".to_string()
    }

    fn emit_begin(&self, mut body: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let mut out = String::new();
        while heap.is_pair(body) {
            let is_last = heap.cdr(body) == Val::NIL;
            if is_last {
                out.push_str(&self.emit_expr(heap.car(body), heap, syms, indent));
            } else {
                let code = self.emit_expr_inline(heap.car(body), heap, syms);
                let pad = "    ".repeat(indent);
                out.push_str(&format!("{pad}{code};\n"));
            }
            body = heap.cdr(body);
        }
        out
    }

    fn emit_cond(&self, mut clauses: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let mut out = String::new();
        let mut first = true;

        while heap.is_pair(clauses) {
            let clause = heap.car(clauses);
            let test = heap.car(clause);
            let body = heap.cdr(clause);

            if heap.is_symbol(test) && syms.sym_eq(test, "else") {
                out.push_str(&format!("{pad}}} else {{\n"));
                out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                out.push_str(&format!("{pad}}}\n"));
                return out;
            }

            let test_code = self.emit_expr_inline(test, heap, syms);
            if first {
                out.push_str(&format!("{pad}if is_true({test_code}) {{\n"));
                first = false;
            } else {
                out.push_str(&format!("{pad}}} else if is_true({test_code}) {{\n"));
            }
            out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
            clauses = heap.cdr(clauses);
        }

        if !first {
            out.push_str(&format!("{pad}}} else {{\n{pad}    Val::NIL\n{pad}}}\n"));
        }
        out
    }

    fn emit_arith(&self, op: &str, rest: Val, heap: &Heap, syms: &SymbolTable, pad: &str) -> String {
        let a = self.emit_expr_inline(heap.car(rest), heap, syms);
        let b = self.emit_expr_inline(heap.car(heap.cdr(rest)), heap, syms);
        let rust_op = match op {
            "+" => "+", "-" => "-", "*" => "*", "/" => "/",
            "quotient" => "/", "remainder" => "%", "modulo" => "%",
            _ => "+"
        };
        format!("{pad}Val::fixnum({a}.as_fixnum().unwrap() {rust_op} {b}.as_fixnum().unwrap())\n")
    }

    fn emit_and_chain(&self, parts: &[String]) -> String {
        if parts.is_empty() { return "Val::fixnum(1)".to_string(); }
        if parts.len() == 1 { return parts[0].clone(); }
        let mut s = format!("{{ let _v = {}; if !is_true(_v) {{ _v }}", parts[0]);
        for p in &parts[1..parts.len()-1] {
            s.push_str(&format!(" else {{ let _v = {}; if !is_true(_v) {{ _v }}", p));
        }
        s.push_str(&format!(" else {{ {} }}", parts.last().unwrap()));
        for _ in 0..parts.len()-1 { s.push_str(" }"); }
        s.push_str(" }");
        s
    }

    fn emit_or_chain(&self, parts: &[String]) -> String {
        if parts.is_empty() { return "Val::NIL".to_string(); }
        if parts.len() == 1 { return parts[0].clone(); }
        // Build: { let _v = p0; if is_true(_v) { _v } else { let _v = p1; if is_true(_v) { _v } else { pN } } }
        let mut s = format!("{{ let _v = {}; if is_true(_v) {{ _v }}", parts[0]);
        for p in &parts[1..parts.len()-1] {
            s.push_str(&format!(" else {{ let _v = {}; if is_true(_v) {{ _v }}", p));
        }
        s.push_str(&format!(" else {{ {} }}", parts.last().unwrap()));
        // Close: one for each else block + one for the outer
        for _ in 0..parts.len()-1 { s.push_str(" }"); }
        s
    }

    fn emit_case(&self, rest: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let key_expr = heap.car(rest);
        let key_code = self.emit_expr_inline(key_expr, heap, syms);
        let mut out = format!("{pad}{{ let _key = {key_code};\n");

        let mut clauses = heap.cdr(rest);
        let mut first = true;
        while heap.is_pair(clauses) {
            let clause = heap.car(clauses);
            let datums = heap.car(clause);
            let body = heap.cdr(clause);

            if heap.is_symbol(datums) && syms.sym_eq(datums, "else") {
                out.push_str(&format!("{pad}}} else {{\n"));
                out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
                out.push_str(&format!("{pad}}}}}\n"));
                return out;
            }

            // Build condition: _key == datum1 || _key == datum2 || ...
            let mut conds = Vec::new();
            let mut d = datums;
            while heap.is_pair(d) {
                let datum = heap.car(d);
                let dc = self.emit_datum(datum, heap, syms);
                conds.push(format!("_key == {dc}"));
                d = heap.cdr(d);
            }
            let cond = conds.join(" || ");

            if first {
                out.push_str(&format!("{pad}if {cond} {{\n"));
                first = false;
            } else {
                out.push_str(&format!("{pad}}} else if {cond} {{\n"));
            }
            out.push_str(&self.emit_begin(body, heap, syms, indent + 1));
            clauses = heap.cdr(clauses);
        }
        if !first {
            out.push_str(&format!("{pad}}} else {{\n{pad}    Val::NIL\n{pad}}}}}\n"));
        } else {
            out.push_str(&format!("{pad}Val::NIL }}\n"));
        }
        out
    }

    fn emit_do(&self, rest: Val, heap: &Heap, syms: &SymbolTable, indent: usize) -> String {
        let pad = "    ".repeat(indent);
        let var_specs = heap.car(rest);
        let test_clause = heap.car(heap.cdr(rest));
        let commands = heap.cdr(heap.cdr(rest));

        let mut out = format!("{pad}{{\n");

        // Initialize vars
        let mut vars = Vec::new();
        let mut vs = var_specs;
        while heap.is_pair(vs) {
            let spec = heap.car(vs);
            let var = heap.car(spec);
            let init = heap.car(heap.cdr(spec));
            let step_rest = heap.cdr(heap.cdr(spec));
            let step = if heap.is_pair(step_rest) { Some(heap.car(step_rest)) } else { None };

            let vname = syms.symbol_name(var).unwrap_or("_").to_string();
            let init_code = self.emit_expr_inline(init, heap, syms);
            out.push_str(&format!("{pad}    let mut {} = {init_code};\n", rust_ident(&vname)));
            vars.push((vname, step));
            vs = heap.cdr(vs);
        }

        let test_expr = heap.car(test_clause);
        let result_exprs = heap.cdr(test_clause);

        out.push_str(&format!("{pad}    loop {{\n"));

        // Test
        let test_code = self.emit_expr_inline(test_expr, heap, syms);
        out.push_str(&format!("{pad}        if is_true({test_code}) {{ break\n"));
        out.push_str(&self.emit_begin(result_exprs, heap, syms, indent + 3));
        out.push_str(&format!("{pad}        }}\n"));

        // Commands
        let mut cmd = commands;
        while heap.is_pair(cmd) {
            let code = self.emit_expr_inline(heap.car(cmd), heap, syms);
            out.push_str(&format!("{pad}        {code};\n"));
            cmd = heap.cdr(cmd);
        }

        // Step vars (compute all first, then assign)
        let mut step_codes = Vec::new();
        for (vname, step) in &vars {
            if let Some(step_expr) = step {
                step_codes.push((vname.clone(), self.emit_expr_inline(*step_expr, heap, syms)));
            }
        }
        for (vname, code) in &step_codes {
            out.push_str(&format!("{pad}        let _next_{vn} = {code};\n", vn = rust_ident(vname)));
        }
        for (vname, _) in &step_codes {
            out.push_str(&format!("{pad}        {vn} = _next_{vn};\n", vn = rust_ident(vname)));
        }

        out.push_str(&format!("{pad}    }}\n"));
        out.push_str(&format!("{pad}}}\n"));
        out
    }

    fn emit_datum(&self, datum: Val, heap: &Heap, syms: &SymbolTable) -> String {
        if datum.is_fixnum() {
            return format!("Val::fixnum({})", datum.as_fixnum().unwrap());
        }
        if datum == Val::NIL {
            return "Val::NIL".to_string();
        }
        if heap.is_symbol(datum) {
            // Quoted symbol — for now, emit as a fixnum hash
            let name = syms.symbol_name(datum).unwrap_or("_");
            let hash = name.bytes().fold(0i64, |acc, b| acc.wrapping_mul(31).wrapping_add(b as i64));
            return format!("Val::fixnum({hash}) /* '{name} */");
        }
        "Val::NIL".to_string()
    }
}

/// Convert a Scheme identifier to a valid Rust identifier.
fn rust_ident(name: &str) -> String {
    let mut s = String::new();
    for c in name.chars() {
        match c {
            '-' => s.push('_'),
            '?' => s.push_str("_p"),
            '!' => s.push_str("_bang"),
            '>' => s.push_str("_to_"),
            '<' => s.push_str("_lt_"),
            '=' => s.push_str("_eq_"),
            '*' => s.push_str("_star_"),
            '+' => s.push_str("_plus_"),
            '/' => s.push_str("_div_"),
            _ => s.push(c),
        }
    }
    // Avoid Rust keywords
    match s.as_str() {
        "type" => "type_".to_string(),
        "match" => "match_".to_string(),
        "loop" => "loop_".to_string(),
        "fn" => "fn_".to_string(),
        "let" => "let_".to_string(),
        "if" => "if_".to_string(),
        "else" => "else_".to_string(),
        "return" => "return_".to_string(),
        "mod" => "mod_".to_string(),
        _ => s,
    }
}

/// The minimal runtime that gets inlined into compiled output.
/// Uses a global heap to avoid mutable borrow issues in nested expressions.
const RUNTIME_PRELUDE: &str = r#"
// ── Inline runtime ───────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq)]
struct Val(i64);

impl Val {
    const NIL: Val = Val(0);

    #[inline(always)]
    const fn fixnum(n: i64) -> Val { Val((n << 1) | 1) }

    #[inline(always)]
    const fn rib(idx: usize) -> Val { Val((idx as i64) << 1) }

    #[inline(always)]
    fn is_fixnum(self) -> bool { (self.0 & 1) != 0 }

    #[inline(always)]
    fn as_fixnum(self) -> Option<i64> {
        if self.is_fixnum() { Some(self.0 >> 1) } else { None }
    }

    #[inline(always)]
    fn as_rib(self) -> usize { (self.0 >> 1) as usize }
}

#[derive(Clone, Copy)]
struct Rib { car: Val, cdr: Val, tag: u8 }

static mut HEAP: Vec<Rib> = Vec::new();

fn heap_init() {
    unsafe { HEAP = Vec::with_capacity(65536);
             HEAP.push(Rib { car: Val::NIL, cdr: Val::NIL, tag: TOP }); }
}

#[inline]
fn cons(car: Val, cdr: Val) -> Val {
    unsafe {
        let idx = HEAP.len();
        HEAP.push(Rib { car, cdr, tag: T_PAIR });
        Val::rib(idx)
    }
}

#[inline(always)]
fn car(v: Val) -> Val {
    if v.is_fixnum() || v == Val::NIL { return Val::NIL; }
    unsafe { HEAP[v.as_rib()].car }
}

#[inline(always)]
fn cdr(v: Val) -> Val {
    if v.is_fixnum() || v == Val::NIL { return Val::NIL; }
    unsafe { HEAP[v.as_rib()].cdr }
}

#[inline(always)]
fn is_true(v: Val) -> bool {
    v != Val::NIL && v.0 != 0
}

#[inline(always)]
fn bool_to_val(b: bool) -> Val {
    if b { Val::fixnum(1) } else { Val::NIL }
}

fn set_car(v: Val, new_car: Val) {
    if !v.is_fixnum() && v != Val::NIL {
        unsafe { HEAP[v.as_rib()].car = new_car; }
    }
}

fn set_cdr(v: Val, new_cdr: Val) {
    if !v.is_fixnum() && v != Val::NIL {
        unsafe { HEAP[v.as_rib()].cdr = new_cdr; }
    }
}

fn append(a: Val, b: Val) -> Val {
    if a == Val::NIL || a.is_fixnum() { return b; }
    let c = car(a);
    let rest = append(cdr(a), b);
    cons(c, rest)
}

fn display(v: Val) {
    if v == Val::NIL { print!("()"); }
    else if let Some(n) = v.as_fixnum() { print!("{n}"); }
    else {
        unsafe {
            let rib = &HEAP[v.as_rib()];
            if rib.tag == T_PAIR {
                print!("(");
                display(rib.car);
                let mut rest = rib.cdr;
                while rest != Val::NIL && !rest.is_fixnum() && HEAP[rest.as_rib()].tag == T_PAIR {
                    print!(" ");
                    display(HEAP[rest.as_rib()].car);
                    rest = HEAP[rest.as_rib()].cdr;
                }
                if rest != Val::NIL {
                    print!(" . ");
                    display(rest);
                }
                print!(")");
            } else {
                print!("<rib>");
            }
        }
    }
}
"#;

/// Compile a Scheme source string to a Rust program string.
pub fn compile(src: &str) -> String {
    let mut heap = Heap::new();
    let mut syms = SymbolTable::new();
    let exprs = crate::reader::read_all(src, &mut heap, &mut syms)
        .unwrap_or_default();
    let mut compiler = Compiler::new();
    compiler.process(&exprs, &heap, &syms);
    compiler.emit_rust(&heap, &syms)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compile_fib() {
        let code = compile("
            (define (fib n)
              (if (< n 2) n
                  (+ (fib (- n 1)) (fib (- n 2)))))
            (display (fib 10))
            (newline)
        ");
        assert!(code.contains("fn fib("));
        assert!(code.contains("fn main()"));
        assert!(code.contains("display"));
    }

    #[test]
    fn compile_arithmetic() {
        let code = compile("(display (+ 3 4))");
        assert!(code.contains("Val::fixnum(3)"));
        assert!(code.contains("Val::fixnum(4)"));
    }

    #[test]
    fn compiled_output_compiles() {
        // Write the compiled output to a temp file and compile it with rustc
        let code = compile("
            (define (fact n)
              (if (= n 0) 1
                  (* n (fact (- n 1)))))
            (display (fact 10))
            (newline)
        ");

        let path = "/tmp/kamea_test_compiled.rs";
        std::fs::write(path, &code).unwrap();
        let output = std::process::Command::new("rustc")
            .args(["-O", "-o", "/tmp/kamea_test_compiled", path])
            .output()
            .expect("failed to run rustc");

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            panic!("rustc failed:\n{stderr}\n\nGenerated code:\n{code}");
        }

        // Run it and check output
        let run = std::process::Command::new("/tmp/kamea_test_compiled")
            .output()
            .expect("failed to run compiled program");
        let stdout = String::from_utf8_lossy(&run.stdout);
        assert_eq!(stdout.trim(), "3628800");
    }

    #[test]
    fn compiled_nqueens() {
        let code = compile("
            (define (abs-diff a b) (if (> a b) (- a b) (- b a)))
            (define (safe? queen dist placed)
              (if (null? placed) 42
                (let ((q (car placed)))
                  (cond ((= queen q) '())
                        ((= (abs-diff queen q) dist) '())
                        (else (safe? queen (+ dist 1) (cdr placed)))))))
            (define (nqueens-count n row placed)
              (if (= row n) 1
                (count-cols n 0 row placed)))
            (define (count-cols n col row placed)
              (if (= col n) 0
                (+ (if (safe? col 1 placed)
                     (nqueens-count n (+ row 1) (cons col placed))
                     0)
                   (count-cols n (+ col 1) row placed))))
            (define (nqueens n) (nqueens-count n 0 '()))
            (display (nqueens 8))
            (newline)
        ");

        let path = "/tmp/kamea_nqueens_compiled.rs";
        std::fs::write(path, &code).unwrap();
        let output = std::process::Command::new("rustc")
            .args(["-O", "-o", "/tmp/kamea_nqueens_compiled", path])
            .output()
            .expect("failed to run rustc");

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            panic!("rustc failed:\n{stderr}\n\nGenerated code:\n{code}");
        }

        let run = std::process::Command::new("/tmp/kamea_nqueens_compiled")
            .output()
            .expect("failed to run compiled program");
        let stdout = String::from_utf8_lossy(&run.stdout);
        assert_eq!(stdout.trim(), "92");
    }

    /// Helper: compile, build with rustc -O, run, return stdout
    fn compile_and_run(src: &str) -> String {
        use std::sync::atomic::{AtomicUsize, Ordering};
        static COUNTER: AtomicUsize = AtomicUsize::new(0);
        let id = COUNTER.fetch_add(1, Ordering::SeqCst);

        let code = compile(src);
        let rs_path = format!("/tmp/wispy_test_{id}.rs");
        let bin_path = format!("/tmp/wispy_test_{id}");
        std::fs::write(&rs_path, &code).unwrap();
        let output = std::process::Command::new("rustc")
            .args(["-O", "-o", &bin_path, &rs_path])
            .output()
            .expect("failed to run rustc");
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            panic!("rustc failed:\n{stderr}\n\nGenerated:\n{code}");
        }
        let run = std::process::Command::new(&bin_path)
            .output()
            .expect("failed to run");
        let _ = std::fs::remove_file(&rs_path);
        let _ = std::fs::remove_file(&bin_path);
        String::from_utf8_lossy(&run.stdout).to_string()
    }

    #[test]
    fn compiled_let_star() {
        let out = compile_and_run("
            (define (f) (let* ((x 1) (y (+ x 10))) (display y)))
            (f) (newline)
        ");
        assert_eq!(out.trim(), "11");
    }

    #[test]
    fn compiled_cond() {
        let out = compile_and_run("
            (define (classify n)
              (cond ((< n 0) 1)
                    ((= n 0) 2)
                    (else 3)))
            (display (classify (- 0 5)))
            (display (classify 0))
            (display (classify 7))
            (newline)
        ");
        assert_eq!(out.trim(), "123");
    }

    #[test]
    fn compiled_or() {
        let out = compile_and_run("
            (define (f) (or 0 0 42))
            (display (f)) (newline)
        ");
        // 0 is truthy (non-NIL fixnum), so result is 0
        assert_eq!(out.trim(), "0");
    }

    #[test]
    fn compiled_variadic_plus() {
        let out = compile_and_run("(display (+ 1 2 3 4 5)) (newline)");
        assert_eq!(out.trim(), "15");
    }

    #[test]
    fn compiled_list_ops() {
        let out = compile_and_run("
            (define (sum-list lst)
              (if (null? lst) 0
                  (+ (car lst) (sum-list (cdr lst)))))
            (display (sum-list (list 10 20 30))) (newline)
            (display (length (list 1 2 3 4 5))) (newline)
        ");
        assert_eq!(out.trim(), "60\n5");
    }

    #[test]
    fn compiled_set_bang() {
        let out = compile_and_run("
            (define (f n) (if (= n 0) 99 (f (- n 1))))
            (display (f 5)) (newline)
        ");
        assert_eq!(out.trim(), "99");
    }

    #[test]
    fn compiled_abs_max_min() {
        let out = compile_and_run("
            (display (abs -7))
            (display (max 3 9))
            (display (min 3 9))
            (newline)
        ");
        assert_eq!(out.trim(), "793");
    }

    #[test]
    fn compiled_predicates() {
        let out = compile_and_run("
            (define (show x) (display (if x 1 0)))
            (show (null? '()))
            (show (pair? (cons 1 2)))
            (show (number? 5))
            (show (zero? 0))
            (show (positive? 5))
            (newline)
        ");
        assert_eq!(out.trim(), "11111");
    }

    #[test]
    fn compiled_do_loop() {
        let out = compile_and_run("
            (define (sum-1-to-10)
              (do ((i 1 (+ i 1))
                   (sum 0 (+ sum i)))
                  ((> i 10) sum)))
            (display (sum-1-to-10)) (newline)
        ");
        assert_eq!(out.trim(), "55");
    }

    #[test]
    fn compiled_gcd() {
        let out = compile_and_run("
            (display (gcd 12 8)) (newline)
        ");
        assert_eq!(out.trim(), "4");
    }

    #[test]
    fn compiled_display_list() {
        let out = compile_and_run("
            (display (list 1 2 3)) (newline)
        ");
        assert_eq!(out.trim(), "(1 2 3)");
    }

    #[test]
    fn compiled_reverse() {
        let out = compile_and_run("
            (display (reverse (list 1 2 3))) (newline)
        ");
        assert_eq!(out.trim(), "(3 2 1)");
    }

    #[test]
    fn compiled_append() {
        let out = compile_and_run("
            (display (append (list 1 2) (list 3 4))) (newline)
        ");
        assert_eq!(out.trim(), "(1 2 3 4)");
    }

    #[test]
    fn compiled_eq() {
        let out = compile_and_run("
            (define (f) (if (eq? 1 1) 10 20))
            (display (f)) (newline)
        ");
        assert_eq!(out.trim(), "10");
    }
}
